// Code generated by protoc-gen-go. DO NOT EDIT.
// source: genbank.proto

package gbparse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Genbank struct {
	LOCUS      string       `protobuf:"bytes,1,opt,name=LOCUS" json:"LOCUS,omitempty"`
	ACCESSION  string       `protobuf:"bytes,2,opt,name=ACCESSION" json:"ACCESSION,omitempty"`
	DEFINITION string       `protobuf:"bytes,3,opt,name=DEFINITION" json:"DEFINITION,omitempty"`
	VERSION    string       `protobuf:"bytes,4,opt,name=VERSION" json:"VERSION,omitempty"`
	DBLINK     []string     `protobuf:"bytes,5,rep,name=DBLINK" json:"DBLINK,omitempty"`
	KEYWORDS   string       `protobuf:"bytes,6,opt,name=KEYWORDS" json:"KEYWORDS,omitempty"`
	SOURCE     string       `protobuf:"bytes,7,opt,name=SOURCE" json:"SOURCE,omitempty"`
	ORGANISM   []string     `protobuf:"bytes,8,rep,name=ORGANISM" json:"ORGANISM,omitempty"`
	COMMENT    string       `protobuf:"bytes,9,opt,name=COMMENT" json:"COMMENT,omitempty"`
	SEQUENCE   string       `protobuf:"bytes,10,opt,name=SEQUENCE" json:"SEQUENCE,omitempty"`
	CONTIG     string       `protobuf:"bytes,11,opt,name=CONTIG" json:"CONTIG,omitempty"`
	REFERENCES []*Reference `protobuf:"bytes,12,rep,name=REFERENCES" json:"REFERENCES,omitempty"`
	FEATURES   []*Feature   `protobuf:"bytes,13,rep,name=FEATURES" json:"FEATURES,omitempty"`
}

func (m *Genbank) Reset()                    { *m = Genbank{} }
func (m *Genbank) String() string            { return proto.CompactTextString(m) }
func (*Genbank) ProtoMessage()               {}
func (*Genbank) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Genbank) GetLOCUS() string {
	if m != nil {
		return m.LOCUS
	}
	return ""
}

func (m *Genbank) GetACCESSION() string {
	if m != nil {
		return m.ACCESSION
	}
	return ""
}

func (m *Genbank) GetDEFINITION() string {
	if m != nil {
		return m.DEFINITION
	}
	return ""
}

func (m *Genbank) GetVERSION() string {
	if m != nil {
		return m.VERSION
	}
	return ""
}

func (m *Genbank) GetDBLINK() []string {
	if m != nil {
		return m.DBLINK
	}
	return nil
}

func (m *Genbank) GetKEYWORDS() string {
	if m != nil {
		return m.KEYWORDS
	}
	return ""
}

func (m *Genbank) GetSOURCE() string {
	if m != nil {
		return m.SOURCE
	}
	return ""
}

func (m *Genbank) GetORGANISM() []string {
	if m != nil {
		return m.ORGANISM
	}
	return nil
}

func (m *Genbank) GetCOMMENT() string {
	if m != nil {
		return m.COMMENT
	}
	return ""
}

func (m *Genbank) GetSEQUENCE() string {
	if m != nil {
		return m.SEQUENCE
	}
	return ""
}

func (m *Genbank) GetCONTIG() string {
	if m != nil {
		return m.CONTIG
	}
	return ""
}

func (m *Genbank) GetREFERENCES() []*Reference {
	if m != nil {
		return m.REFERENCES
	}
	return nil
}

func (m *Genbank) GetFEATURES() []*Feature {
	if m != nil {
		return m.FEATURES
	}
	return nil
}

type Reference struct {
	Number  int32  `protobuf:"varint,1,opt,name=Number" json:"Number,omitempty"`
	ORIGIN  string `protobuf:"bytes,2,opt,name=ORIGIN" json:"ORIGIN,omitempty"`
	AUTHORS string `protobuf:"bytes,3,opt,name=AUTHORS" json:"AUTHORS,omitempty"`
	CONSRTM string `protobuf:"bytes,4,opt,name=CONSRTM" json:"CONSRTM,omitempty"`
	TITLE   string `protobuf:"bytes,5,opt,name=TITLE" json:"TITLE,omitempty"`
	JOURNAL string `protobuf:"bytes,6,opt,name=JOURNAL" json:"JOURNAL,omitempty"`
	PUBMED  string `protobuf:"bytes,7,opt,name=PUBMED" json:"PUBMED,omitempty"`
}

func (m *Reference) Reset()                    { *m = Reference{} }
func (m *Reference) String() string            { return proto.CompactTextString(m) }
func (*Reference) ProtoMessage()               {}
func (*Reference) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Reference) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Reference) GetORIGIN() string {
	if m != nil {
		return m.ORIGIN
	}
	return ""
}

func (m *Reference) GetAUTHORS() string {
	if m != nil {
		return m.AUTHORS
	}
	return ""
}

func (m *Reference) GetCONSRTM() string {
	if m != nil {
		return m.CONSRTM
	}
	return ""
}

func (m *Reference) GetTITLE() string {
	if m != nil {
		return m.TITLE
	}
	return ""
}

func (m *Reference) GetJOURNAL() string {
	if m != nil {
		return m.JOURNAL
	}
	return ""
}

func (m *Reference) GetPUBMED() string {
	if m != nil {
		return m.PUBMED
	}
	return ""
}

type Feature struct {
	TYPE         string       `protobuf:"bytes,1,opt,name=TYPE" json:"TYPE,omitempty"`
	IsCompliment bool         `protobuf:"varint,2,opt,name=isCompliment" json:"isCompliment,omitempty"`
	IsJoined     bool         `protobuf:"varint,3,opt,name=isJoined" json:"isJoined,omitempty"`
	START        string       `protobuf:"bytes,4,opt,name=START" json:"START,omitempty"`
	STOP         string       `protobuf:"bytes,5,opt,name=STOP" json:"STOP,omitempty"`
	QUALIFIERS   []*Qualifier `protobuf:"bytes,6,rep,name=QUALIFIERS" json:"QUALIFIERS,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Feature) GetTYPE() string {
	if m != nil {
		return m.TYPE
	}
	return ""
}

func (m *Feature) GetIsCompliment() bool {
	if m != nil {
		return m.IsCompliment
	}
	return false
}

func (m *Feature) GetIsJoined() bool {
	if m != nil {
		return m.IsJoined
	}
	return false
}

func (m *Feature) GetSTART() string {
	if m != nil {
		return m.START
	}
	return ""
}

func (m *Feature) GetSTOP() string {
	if m != nil {
		return m.STOP
	}
	return ""
}

func (m *Feature) GetQUALIFIERS() []*Qualifier {
	if m != nil {
		return m.QUALIFIERS
	}
	return nil
}

type Qualifier struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Qualifier) Reset()                    { *m = Qualifier{} }
func (m *Qualifier) String() string            { return proto.CompactTextString(m) }
func (*Qualifier) ProtoMessage()               {}
func (*Qualifier) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Qualifier) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Qualifier) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Genbank)(nil), "gbparse.Genbank")
	proto.RegisterType((*Reference)(nil), "gbparse.Reference")
	proto.RegisterType((*Feature)(nil), "gbparse.Feature")
	proto.RegisterType((*Qualifier)(nil), "gbparse.Qualifier")
}

func init() { proto.RegisterFile("genbank.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x93, 0x4f, 0x6e, 0xdb, 0x3c,
	0x10, 0xc5, 0xe1, 0xcf, 0xf1, 0x1f, 0x31, 0x09, 0x10, 0x10, 0x1f, 0x0a, 0xa2, 0x28, 0x0a, 0xc3,
	0x2b, 0x2f, 0x0a, 0x2f, 0x92, 0x13, 0x28, 0x32, 0xed, 0x32, 0x91, 0x48, 0x7b, 0x48, 0xb5, 0xc8,
	0x52, 0x6e, 0x99, 0x40, 0x88, 0x2d, 0x1b, 0xb2, 0x5d, 0xa0, 0xa7, 0xe8, 0x71, 0xba, 0xe8, 0xe5,
	0x8a, 0x21, 0x29, 0xd5, 0xd9, 0xf1, 0xc7, 0x99, 0xa7, 0x79, 0xe4, 0xa3, 0xc8, 0xf5, 0x8b, 0xad,
	0xd6, 0x45, 0xf5, 0x3a, 0xdd, 0xd7, 0xbb, 0xe3, 0x8e, 0x0e, 0x5e, 0xd6, 0xfb, 0xa2, 0x3e, 0xd8,
	0xf1, 0xaf, 0x2e, 0x19, 0x2c, 0x7c, 0x89, 0xfe, 0x4f, 0x7a, 0xa9, 0x4a, 0x72, 0xcd, 0x3a, 0xa3,
	0xce, 0x24, 0x02, 0x0f, 0xf4, 0x03, 0x89, 0xe2, 0x24, 0xe1, 0x5a, 0x0b, 0x25, 0xd9, 0x7f, 0xae,
	0xf2, 0x6f, 0x83, 0x7e, 0x24, 0x64, 0xc6, 0xe7, 0x42, 0x0a, 0x83, 0xe5, 0xae, 0x2b, 0x9f, 0xed,
	0x50, 0x46, 0x06, 0x5f, 0x38, 0x38, 0xed, 0x85, 0x2b, 0x36, 0x48, 0xdf, 0x91, 0xfe, 0xec, 0x3e,
	0x15, 0xf2, 0x91, 0xf5, 0x46, 0xdd, 0x49, 0x04, 0x81, 0xe8, 0x7b, 0x32, 0x7c, 0xe4, 0x4f, 0x5f,
	0x15, 0xcc, 0x34, 0xeb, 0x3b, 0x49, 0xcb, 0xa8, 0xd1, 0x2a, 0x87, 0x84, 0xb3, 0x81, 0xab, 0x04,
	0x42, 0x8d, 0x82, 0x45, 0x2c, 0x85, 0xce, 0xd8, 0xd0, 0x7d, 0xad, 0x65, 0x74, 0x90, 0xa8, 0x2c,
	0xe3, 0xd2, 0xb0, 0xc8, 0x3b, 0x08, 0x88, 0x2a, 0xcd, 0x57, 0x39, 0x97, 0x09, 0x67, 0xc4, 0x4f,
	0x6a, 0x18, 0x27, 0x25, 0x4a, 0x1a, 0xb1, 0x60, 0x97, 0x7e, 0x92, 0x27, 0x7a, 0x4b, 0x08, 0xf0,
	0x39, 0x07, 0x6c, 0xd2, 0xec, 0x6a, 0xd4, 0x9d, 0x5c, 0xde, 0xd2, 0x69, 0xb8, 0xcd, 0x29, 0xd8,
	0x67, 0x5b, 0xdb, 0xea, 0x9b, 0x85, 0xb3, 0x2e, 0xfa, 0x89, 0x0c, 0xe7, 0x3c, 0x36, 0x39, 0x70,
	0xcd, 0xae, 0x9d, 0xe2, 0xa6, 0x55, 0xcc, 0x6d, 0x71, 0x3c, 0xd5, 0x16, 0xda, 0x8e, 0xf1, 0xef,
	0x0e, 0x89, 0xda, 0xef, 0xa0, 0x0f, 0x79, 0xda, 0xae, 0x6d, 0xed, 0x42, 0xe9, 0x41, 0x20, 0xdc,
	0x57, 0x20, 0x16, 0xa2, 0x89, 0x24, 0x10, 0x9e, 0x36, 0xce, 0xcd, 0x67, 0x05, 0x3a, 0x84, 0xd1,
	0xa0, 0xbf, 0x07, 0xa9, 0xc1, 0x64, 0x4d, 0x12, 0x01, 0x31, 0x77, 0x23, 0x4c, 0xca, 0x59, 0xcf,
	0xe7, 0xee, 0x00, 0xfb, 0x1f, 0x54, 0x0e, 0x32, 0x4e, 0x43, 0x0c, 0x0d, 0xe2, 0xec, 0x65, 0x7e,
	0x9f, 0xf1, 0x59, 0x93, 0x82, 0xa7, 0xf1, 0x9f, 0x0e, 0x19, 0x84, 0xf3, 0x50, 0x4a, 0x2e, 0xcc,
	0xd3, 0x92, 0x87, 0xa7, 0xe4, 0xd6, 0x74, 0x4c, 0xae, 0xca, 0x43, 0xb2, 0xdb, 0xee, 0x37, 0xe5,
	0xd6, 0x56, 0x47, 0xe7, 0x7c, 0x08, 0x6f, 0xf6, 0x30, 0x93, 0xf2, 0xf0, 0xb0, 0x2b, 0x2b, 0xfb,
	0xdd, 0x1d, 0x60, 0x08, 0x2d, 0xa3, 0x4f, 0x6d, 0x62, 0x30, 0xc1, 0xbf, 0x07, 0x9c, 0xa4, 0x8d,
	0x5a, 0x06, 0xf3, 0x6e, 0x8d, 0x29, 0xad, 0xf2, 0x38, 0x15, 0x73, 0xc1, 0x01, 0x5f, 0xd1, 0xdb,
	0x94, 0x56, 0xa7, 0x62, 0x53, 0x3e, 0x97, 0xb6, 0x86, 0xb3, 0xae, 0xf1, 0x1d, 0x89, 0xda, 0x02,
	0xbd, 0x21, 0xdd, 0x57, 0xfb, 0x33, 0xb8, 0xc7, 0x25, 0x0e, 0xff, 0x51, 0x6c, 0x4e, 0x36, 0xdc,
	0xb7, 0x87, 0x75, 0xdf, 0xfd, 0x4e, 0x77, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x64, 0xbe, 0x46,
	0x83, 0x5f, 0x03, 0x00, 0x00,
}
